github: [acfoltzer, acfoltzer-fastly]
patreon: acfoltzer
ko_fi: acfoltzer
liberapay: acfoltzer
issuehunt: acfoltzer
custom: ["https://www.acfoltzer.net/", "https://www.acfoltzer.net/another_url", "acfoltzer.net/bare_relative_link"]
some_other_thing: ralphie
